In [2]:
import numpy as np

In [ ]:
arr = 

In [ ]:
# 행렬곱, 내적
np.dot(arr.T,arr)

In [ ]:
a = np.arange(6).reshape(2,3)
print(a,'\n')
y = np.swapaxes(a,0,1)
print(y)

y = a.T
y = np.transpose(a)
y = np.transpose(a)
print(y)

In [ ]:
# 1 ~ 100을 아래와 같이 출력하세요.
# [[  1   2   3   4   5   6   7   8   9  10]
#  [ 20  19  18  17  16  15  14  13  12  11]
#  [ 21  22  23  24  25  26  27  28  29  30]
#  [ 40  39  38  37  36  35  34  33  32  31]
#  [ 41  42  43  44  45  46  47  48  49  50]
#  [ 60  59  58  57  56  55  54  53  52  51]
#  [ 61  62  63  64  65  66  67  68  69  70]
#  [ 80  79  78  77  76  75  74  73  72  71]
#  [ 81  82  83  84  85  86  87  88  89  90]
#  [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>
arr = np.arange(1,101).reshape(10,10)
for i in range(10):
    if i % 2 == 1:
        arr[i] = arr[i][::-1]
print(arr, type(arr))

In [ ]:
# (0,1,2)
# 3차원과 2차원을 바꾸는 경우 (1,2,3) > (2,1,3)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')
y = np.transpose(a,(1,0,2))
print(y,y.shape)

In [ ]:
# (1,2,3) > (2,3,1)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')
y = np.transpose(a,(1,2,0))
print(y,y.shape)

In [ ]:
arr = np.arange(16).reshape((2,2,4))
print(arr,'\n','======================================================')
arr2 = arr.transpose((1,0,2))
print(arr2)

In [ ]:
a = np.array([[1,2],[3,4]])
print(a,'\n','===================')       
print(a.T,'\n','===================')    
print(a.transpose((1,0)))                 

In [ ]:
# [과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)
arr = np.arange(16).reshape(2,2,4)        #    axis 0 (3차원) = 2   >>>>   axis 1 (2차원) = 2 
print(arr,arr.shape,'\n')                 #    axis 1 (2차원) = 2   >>>>   axis 0 (3차원) = 2
arr2 = arr.transpose((1,0,2))             #    axis 2 (1차원) = 4   >>>>   axis 2 (1차원) = 4
print(arr2,arr2.shape)


In [ ]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요 (shape 확인)
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')
arr2 = arr.transpose((0,2,1))
print(arr2,arr2.shape)

In [ ]:
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')
arr2 = arr.transpose((0,1,2))
print(arr2,arr2.shape)

In [ ]:
# 나머지를 구할 경우 사용하는 함수
value1 = np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

In [ ]:
# 각 수의 역수를 구해주는 함수
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value))

value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1, dtype = float))

In [ ]:
# 승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

In [ ]:
arr = np.random.randn(10)
#print(arr.mean(),'\n')
#print(arr.std())
arr

In [ ]:
# 양수인 원소의 개수
(arr>0).sum()

In [ ]:
# True가 있는지 검사
bools = np.array([False,False,True,True])
bools.any()

In [ ]:
# 모든 원소가 True인지 검사
bools.all()

In [ ]:
# 삼항식의 벡터화 버전
arr = np.random.randn(4,4)
print(arr,'\n')
print(np.where(arr > 0,2,-2))
print(np.where(arr>0))
print(arr[np.where(arr>0)])

In [ ]:
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0,2,arr)

In [ ]:
# np.sort()
np.random.seed(0)
arr = np.random.randint(1,100,size = 10)
print(arr,'\n')
print(np.sort(arr),'\n')
print(arr)

In [ ]:
sorted = np.sort(arr)
print(sorted)

In [ ]:
# 행렬이 2차원 이상일 때 axis 축 값설정을 통해 행,열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_ar2d_axis0 = np.sort(arr2d, axis = 0)
print(sort_ar2d_axis0,'\n')
sort_ar2d_axis1 = np.sort(arr2d, axis = 1)
print(sort_ar2d_axis1,'\n')

In [ ]:
# ndarray.sort() : 원본 반영
#arr = np.random.randn(6)
np.random.seed(0)
arr = np.random.randint(1,10,size = 10)
print(arr,'\n')
arr.sort()     # 원본 반영
arr
#print(arr)

In [ ]:
# 다차원 배열의 정렬은 sort 매소드에 넘긴 축에 따라 1차원 부분을 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort()     # 원본 반영
print(arr)

In [ ]:
# 열방향 정렬 (default)
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(1)
print(arr)

In [ ]:
# 행방향 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(0)
print(arr)

In [ ]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
print(type(sort_indices))
print(sort_indices)

In [ ]:
# 배열에서 정렬한 후 5% 분위수에 해당하는 원소와 그 안쪽인 원소 출력
np.random.seed(0)
large_arr = np.random.randn(1000)
large_arr.sort()
print(large_arr[int(0.05*len(large_arr))])
print(large_arr[large_arr<=large_arr[int(0.05*len(large_arr))]])

In [ ]:
#배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

In [ ]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

In [ ]:
# 첫 번째 배열의 원소가 두 번째 배열의 원소를 포함하는지 알려주는 불리안 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

In [ ]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 .npy 파일로 저장

arr = np.arange(10)
np.save('some_array',arr)


In [ ]:
np.load('some_array.npy')

In [ ]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr,b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['a']

In [ ]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0] 을 출력하세요.
a = np.ones(10,dtype=int)
for i in range(len(a)):
    if i % 2 == 1:
        a[i] = 0
print(a)


b = np.ones(10,dtype=int)
b_1 = np.array([0,1,0,1,0,1,0,1,0,1])
b[(np.nonzero(b_1))]=0
print(b)

In [ ]:
# Q, a = np.arange(10)에서 [6,7,8,9] 출력
a = np.arange(10)
print(a[6:10])
print(a[a>5])

In [ ]:
# Q. a에서 최대값, 최소값의 인덱스 출력
a = np.arange(1,10)
print(a)
print(np.argmin(a))
print(np.argmax(a))

In [ ]:
# Q. a에서 인덱스 배열을 역순으로 출력
np.argsort(a)[::-1]

In [ ]:
# Q. np.ones((10,10))을 아래와 같이 출력
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

a = np.ones((10,10))
a[1:9,1:9] = 0
a

In [4]:
# [과제] np.ones((5,5))을 아래와 같이 출력하세요.
# array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])
a = np.zeros((9,9))
a[2:7,2:7] = np.ones((5,5))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이출력하세요.(두가지 방식: 인덱싱, tile함수)
# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]])
a = np.zeros((8,8))
for i in range(8):
    if i % 2 == 0:
        for j in range(8):
            if j % 2 == 1:
                a[i,j] = 1
    else:
        for j in range(8):
            if j % 2 == 0:
                a[i,j] = 1
print(a)



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [11]:
a = np.array([[0,1],[1,0]])
b = np.tile(a,(4,4))
print(b)
x = np.zeros((8,8))
x[::2,1::2] = 1
x[1::2,::2] = 1
x


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [9]:
arr = np.zeros((8,8)).astype(int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [10]:
# [도전과제] np.arange(336), reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
# 사용자 정의 함수 이용
def search_index336(a,b,c):
    arr = np.arange(336).reshape(a,b,c)
    while 1:
        try:
            d = int(input('몇 번째 요소의 인덱스를 출력할까요?(1에서 336까지 입력): '))
            if d <= 0:
                raise NotImplementedError
        except:
            print('1 ~ 337 사이 정수만 입력하세요.')
        else:
            for i in range(1,7):
                if d <= i*b*c:
                    p = i-1,((d-1) - ((i-1) * b * c)) // c,((d-1) - ((i-1) * b * c)) % c
                    return print(f'{d}번째 요소의 인덱스는 {p}이고, 값은 {arr[p]}입니다.')
                    break

search_index336(6,7,8)
print('\n========================================================================================')
# 함수 이용
arr = np.arange(336).reshape(6,7,8)
a = np.in1d(arr, [99]).reshape(6,7,8)
print(f"""
100번째 요소의 인덱스: {np.where(a==True)},
100번째 요소의 값: {arr[np.where(a==True)]}""")

1번째 요소의 인덱스는 (0, 0, 0)이고, 값은 0입니다.


100번째 요소의 인덱스: (array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64)),
100번째 요소의 값: [99]


In [ ]:
a = np.arange(336).reshape(6,7,8)
print(a)

In [ ]:
# [도전과제] np.arange(4)를 이용해서 아래와 같이 출력하세요.
# array([[0, 0, 0, 0, 0],
#        [1, 0, 0, 0, 0],
#        [0, 2, 0, 0, 0],
#        [0, 0, 3, 0, 0],
#        [0, 0, 0, 4, 0]])
ar = np.zeros((5,5))
np.diag(np.arange(4)+1, k=-1)

In [ ]:
np.diag(np.diag(np.arange(4)+1, k=-1), k=-1)

In [13]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 점수중에서 난수 값 리턴
print(random.uniform(10,20),'\n') # min,max 사이 float를 리턴
print(random.randrange(10),'\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5,]),'\n') #리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 지정된 개수만큼 리턴
random.shuffle(li)
print(li)

0.7749205532746385 

9 

15.617680017906547 

0 

5 

[4, 3, 2] 

[4, 1, 5, 3, 2]


[numpy random 함수]
- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 균일분포의 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling


In [29]:
print(np.random.randint(6),'\n') # 0~5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1~19까지 정수인 난수 1개
print(np.random.randint(10, size = 10),'\n') # 0~9까지 정수인 난수 10개
print(np.random.randint(10,20,size = 10),'\n') # 10~19까지 정수인 난수 10개
print(np.random.randint(10,20,size = (3,5)),'\n') # 10~19까지 정수인 난수로 3행 5열 배열 생성

1 

4 

[4 6 9 8 4 3 3 3 6 7] 

[14 19 17 19 17 14 12 11 19 17] 

[[15 15 12 13 13]
 [17 11 15 17 10]
 [15 14 12 18 19]] 



In [ ]:
r = np.random.rand(6) # 0~1사이의 균일분포
print(r,'\n')
r.mean()

In [ ]:
# 표준 정규분포
r = np.random.randn(6)
r.mean()

In [24]:
li = np.arange(1,6)
print(li,'\n')
np.random.shuffle(li)
li

[1 2 3 4 5] 



array([1, 2, 4, 3, 5])

In [11]:
np.random.choice(li)

4

In [ ]:
a = np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts = True)
print(index)
print(count)
print(np.unique(a,return_counts = True))

In [ ]:
np.random.uniform(1.0,2.0,10)


In [ ]:
print(np.random.uniform(0,1,(2,3)))

In [ ]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 각각 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

In [6]:
ar = np.random.rand(4,8)
ar

array([[0.17020172, 0.77265495, 0.04834614, 0.92302802, 0.97213558,
        0.14649878, 0.96805823, 0.3578415 ],
       [0.60369954, 0.74042279, 0.09458295, 0.17963775, 0.37752734,
        0.00847059, 0.03301339, 0.09810276],
       [0.31894335, 0.21608136, 0.84017121, 0.95157679, 0.19759198,
        0.44625121, 0.78104333, 0.9756558 ],
       [0.86094578, 0.60339588, 0.08763898, 0.36004756, 0.96061596,
        0.32783499, 0.63552763, 0.19706647]])

In [12]:
# 배열을 데이터프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
df

NameError: name 'ar' is not defined

In [ ]:
print(df[0])
print()
print(df[0][1])
type(df[0])

In [ ]:
columns = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df

In [ ]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력
df_del = pd.DataFrame(ar,index,columns=columns)
del df_del['region']
del df_del['product']
del df_del['price']
del df_del['qty']
del df_del['time']
df_del['id'] = np.dot(df_del['id'],100000).round().astype('int')
df_del['gender'][df_del['gender']>0.5] = '남'
df_del['gender'][df_del['gender']!='남'] = '여'
df_del['age'] = np.dot(df_del['age'],100).round().astype('int')
df_del

In [ ]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력 (선생님풀이)
arr = np.zeros((4,3))
columns = ['id','gender','age']
index = [np.arange(4)]
df2 = pd.DataFrame(arr,index,columns = columns)
df2.id = np.arange(4)
df2.gender = np.random.randint(2,size=4)
df2.age = np.arange(1,5) * 10
df2

[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요(관측지 1000개)
- id : 1 ~ 1000번 일련번호
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80 사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성
- product_19 : 제품코드 11111~99999
- product_20 : 제품코드 11111~99999
- price_19 : 1000 ~ 500000 사이 실수 난수 생성
- price_20 : 1000 ~ 500000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_19 * quantity_19
- sales : 19년 대비 20년 구매금액이 증가면 1, 감소면 0

In [121]:
a = []
for _ in range(1,25):
    a.append(f'{_}'.zfill(2))
np.array(a)
print(a)

['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24']


In [15]:
import string
import warnings
warnings.filterwarnings('ignore')

arr = np.zeros((1000,15))
columns = ['id','gender','age','region','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index = [np.arange(1000)]
df = pd.DataFrame(arr,index,columns = columns)

id_arr = np.arange(1,1001) ; np.random.shuffle(id_arr) ; df.id = id_arr
gender_ar = np.array(['남','여']) ; df.gender = np.array(np.random.choice(gender_ar) for _ in range(1000))
df.age = np.random.randint(80,size = 1000)
df.region = np.random.randint(10,size = 1000)
def code(a):
    li = []
    for _ in range(a):
        result = ""
        for _ in range(2):
            result += random.choice(string.ascii_uppercase)
        for _ in range(3):
            result += random.choice(string.digits)
        li.append(result)
    return np.array(li)
df.product_19 = code(1000)
df.product_20 = code(1000)
df.price_19 = np.random.rand(1000)*499000+1000
df.price_20 = np.random.rand(1000)*499000+1000
df.quantity_19 = np.random.randint(1,101,size=1000)
df.quantity_20 = np.random.randint(1,101,size=1000)
time_ar = []
for _ in range(1,25):                   # df.time_19 = np.random.randint(1,25,size=1000).astype(str)       # 이 방식 안돼..
    time_ar.append(f'{_}'.zfill(2))     # df.time_19 = df.time_19.str.zfill(2)
np.array(time_ar)
df.time_19 = np.array(np.random.choice(time_ar) for _ in range(1000))
df.time_20 = np.array(np.random.choice(time_ar) for _ in range(1000))
# df.time_19 = np.random.randint(1,25,size=1000)
# df.time_20 = np.random.randint(1,25,size=1000)
df.amount_19 = df.price_19 * df.quantity_19
df.amount_20 = df.price_20 * df.quantity_20
df.sales = np.where(df.amount_19<df.amount_20,1,0)
#pd.Series(df.sales).astype(int)
pd.options.display.float_format = '{:.2f}'.format
df

id gender  age  region product_19 product_20  price_19  price_20  \
0    332      남   14       5      MU414      BP835 368654.09  56845.01   
1    251      여   79       6      IU469      NH815 471899.01 457745.37   
2    454      남   65       6      JE305      QY170 154444.19  79291.48   
3    803      여   66       3      WQ225      WG952 166147.80 280855.24   
4    159      여    3       9      SW384      XK442 315491.07  75450.17   
..   ...    ...  ...     ...        ...        ...       ...       ...   
995  987      남   50       4      OJ681      ZP882 134692.36 436041.10   
996  688      여    1       1      RA286      XG162  85930.31 375012.04   
997   90      남    9       4      PR936      FK602 475391.56  70775.37   
998  288      여   56       9      BA381      XP162  36149.39 478230.20   
999  295      남   25       6      JY630      HK886 371229.43 422805.56   

     quantity_19  quantity_20 time_19 time_20   amount_19   amount_20  sales  
0              3           80      12      05  1105962.27  4547600.66      1  
1             76            5      18      19 35864324.57  2288726.83      0  
2             43           69      24      20  6641100.04  5471112.25      0  
3             66           53      09      04 10965754.77 14885327.89      1  
4             36           99      16      16 11357678.69  7469566.34      0  
..           ...          ...     ...     ...         ...         ...    ...  
995           74           87      08      18  9967234.54 37935575.31      1  
996           61            7      02      24  5241748.71  2625084.25      0  
997           60           16      13      24 28523493.69  1132405.99      0  
998           64            4      05      08  2313560.77  1912920.81      0  
999           26           15      24      01  9651965.30  6342083.41      0  

[1000 rows x 15 columns]

In [16]:
#재우씨
import numpy as np
import pandas as pd

customer = 1000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(11111,100000,size = customer)
df.product_20 = np.random.randint(11111,100000,size = customer)

pricearray= np.random.randint(10,500,size = 100000)*100

for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0

df

id gender  age  product_19  product_20  price_19  price_20  \
1        1      M   40       24227       55976     42900     17000   
2        2      F   29       77462       78920     27400     38500   
3        3      F   25       53750       46507     25600     49500   
4        4      M   19       73611       29381     28000     19100   
5        5      F   68       82728       84075      1300     23200   
...    ...    ...  ...         ...         ...       ...       ...   
996    996      M   24       73435       97517      6400     21300   
997    997      M   53       36781       83820     34400     21600   
998    998      M   24       38495       96299     12700      7700   
999    999      F   73       56675       61737     15700     21000   
1000  1000      M   42       88153       76382     10100     32500   

      quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1              76           79       18       20    3260400    1343000      0  
2              66           45        4       19    1808400    1732500      0  
3              55           36       24       18    1408000    1782000      1  
4              71           15        2       17    1988000     286500      0  
5              20           90        3       20      26000    2088000      1  
...           ...          ...      ...      ...        ...        ...    ...  
996             7           76       20       10      44800    1618800      1  
997            28           53       10       24     963200    1144800      1  
998            72           35        8        7     914400     269500      0  
999            54            6        1       17     847800     126000      0  
1000           56           39       13       23     565600    1267500      1  

[1000 rows x 14 columns]