Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행열 연산에 필요한 다양한 함수를 제공
- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드케스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 가능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [2]:
import numpy as np
z = np.arange(10)
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [3]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_array2 = my_arr * 2

Wall time: 12 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 675 ms


In [7]:
# 배열 연산
#np.random.randn 가우시안 표준 정규분포에서 난수 매트릭스 array 생성
data = np.random.randn(2,3) # 2행 3열 표준 정규분포 매트릭스
print(data, "\n")
print(data * 10, '\n')
print(data + data)

[[-0.32134086 -0.19653264  0.13509467]
 [ 0.94969368 -0.79507723 -1.22182422]] 

[[ -3.21340858  -1.96532638   1.35094672]
 [  9.49693678  -7.95077227 -12.21824216]] 

[[-0.64268172 -0.39306528  0.27018934]
 [ 1.89938736 -1.59015445 -2.44364843]]


In [8]:
print(data.shape) # 크기
print(data.dtype) # 데이터 타입
print(data.ndim) # 차원

(2, 3)
float64
2


다차원 배열
<img src = 'numpy차원.jpg' STYLE = 'width:300px;'>

In [9]:
data2 = [[1,2,3,4], [5,6,7,8]]
print(type(data2),"\n")
arr2 = np.array(data2)
print(arr2,type(arr2))

<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [10]:
print(arr2.ndim,'\n')
print(arr2.shape)

2 

(2, 4)


In [11]:
array1 = np.array([1,2,3])
print(array1,type(array1),array1.shape) # (,열)이 아닌 (열,)형태로 출력

[1 2 3] <class 'numpy.ndarray'> (3,)


In [21]:
# 2차원 배열로 2개의 row와 3개의 column으로 구성된 6개의 데이터
arr = np.array([['남현1','남현2','남현3'],['아무개1','아무개2','아무개3']])
print(arr, '\n')
print(arr.ndim,'\n')
print(arr.shape)

[['남현1' '남현2' '남현3']
 ['아무개1' '아무개2' '아무개3']] 

2 

(2, 3)


In [25]:
# 1개의 row와 3개의 column으로 구성된 2차원 배열
array21 = np.array([[1,2,3]])
print(array21, '\n')
print(array21.ndim,'\n')
print(array21.shape)

[[1 2 3]] 

2 

(1, 3)


In [28]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(arr3, '\n')
print(arr3.ndim,'\n')
print(arr3.shape)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]] 

3 

(3, 2, 4)


In [3]:
# 경고 메세지 무시
import warnings
warnings.filterwarnings('ignore')

배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [30]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [36]:
print(np.ones((2,3,2),dtype=int))

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [38]:
ar1 = np.full((2,2),5)
print(ar1)

[[5 5]
 [5 5]]


In [41]:
# 항등행렬, 단위행렬
ar2 = np.eye(3)
print(ar2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성
a = np.zeros_like([[1,2,3],
                 [4,5,6]],dtype=int)
print(a,'\n')
b = np.ones_like([[1,2,3],
                 [4,5,6]],dtype=int)
print(b,'\n')
c = np.full_like([[1,2,3],
                 [4,5,6]],5,dtype=int)
print(c,'\n')

[[0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]] 

[[5 5 5]
 [5 5 5]] 



In [48]:
# arange 함수: python의 range함수의 배열 버전
arr1 = np.arange(15)

arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
arr2 = arr1.reshape(3,5)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [52]:
# Q. array1을 생성하고 reshape 함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요.
array1 = np.arange(10)
array2 = array1.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
# Q. 0~29 일차원 배열을 생성한 후 다시 2,3차원 배열로 변환하여 출력
array1 = np.arange(30)
array2 = array1.reshape(2,15)
array3 = array1.reshape(2,3,5)
print(array2, '\n')
print(array3)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [59]:
# reshape(-1,-1)이용, 차원 변경
array1 = np.arange(30)
ar12 = array1.reshape(3,-1)
print(ar12,ar12.shape,'\n')
ar13 = array1.reshape(-1,2,5)
print(ar13,ar13.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [69]:
# 2 > 1, 3차원으로 변환
print(ar12.reshape(-1,),ar12.reshape(-1).shape)
print(ar12.reshape(-1,2,5),ar12.reshape(-1,2,5).shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [72]:
# 3 > 1, 2차원으로 변환하여 출력
ar3 = ar12.reshape(-1,2,5)
ar1 = ar3.reshape(-1,)
ar2 = ar1.reshape(3,-1)
print(ar2,ar2.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10)


행렬의 종류
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A행렬을 곱하였을 때 항등행렬이 나오는 행렬


In [76]:
# 정방행렬
a = np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [77]:
# 항등행렬, 단위행렬
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
# 영행렬
a = np.zeros((3,3),dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

ndarray 데이터 형태 지정 및 변경
<img src = '데이터형태.jpg' STYLE = 'width:300px;'>

In [81]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([1,2,3],dtype = np.int32)
print(arr1,arr1.dtype,'\n')
print(arr2,arr2.dtype)

[1. 2. 3.] float64 

[1 2 3] int32


In [83]:
# 타입 변경
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [2]:
import numpy as np
np.ones(10,)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
# empty 함수 : shape와 dtype 을 입력 받아 초기화되지 않은 배열을 만들어준다. 
# empty 함수를 실행할 때마다 값이 다른 것을 확인할 수 있다. 
# 이는 해당 메모리 영역에 어떤 데이터가 남아있었던지 상관없이 그대로 영역의 주소만 알려줄 뿐,
# 초기화는 사용자에게 맡기기 때문이다.
print(np.empty(shape = (10,),dtype=np.int8))
print(np.zeros(shape = (10,),dtype=np.int8))

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]


In [108]:
arr = np.array([1,2,3,4],dtype='S')
print(arr,arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [113]:
arr1 = arr.astype(float)
print(arr1, arr1.dtype)

[1. 2. 3. 4.] float64


In [51]:
# 정수와 실수로 구성된 list_e = [1,2.2.3,3]을 numpy를 이용해서 실수형과 정수형으로 각각 출력하세요
list_e = [1,2,2.3,3]
print(np.array(list_e, dtype = float))
print(np.array(list_e, dtype = int))

[1.  2.  2.3 3. ]
[1 2 2 3]


In [55]:
# 배열의 산술 연산
#arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)

In [56]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [57]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [62]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.,]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [63]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [69]:
# 기본 사칙연산
value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)
print(value1 + value2)
print(np.add(value1,value2),'\n')
print(value2 - value1)
print(np.subtract(value2,value1),'\n')
print(value1 * value2)
print(np.multiply(value1,value2),'\n')
print(value2 / value1)
print(np.divide(value2,value1),'\n')

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]] 



In [34]:
arr = np.random.randn(5,4)
arr

array([[-0.80999993, -0.8757762 , -1.02729183,  1.59523107],
       [ 0.45390194, -0.8366492 ,  1.61331095, -0.01610452],
       [ 2.50693509,  0.62024051, -0.61449838, -1.75301377],
       [-0.72121208,  0.2551378 , -0.23103629, -1.28748455],
       [ 2.272958  ,  0.16849544,  0.80068078,  1.24972809]])

In [35]:
arr.mean().round(4)

0.1682

In [36]:
arr.mean(axis = 1)

array([-0.27945922,  0.30361479,  0.18991586, -0.49614878,  1.12296558])

In [37]:
arr.mean(axis = 0)

array([ 0.7405166 , -0.13371033,  0.10823305, -0.04232874])

In [38]:
arr.sum().round(4)

3.3636

In [39]:
arr.cumprod()    # 주어진 축 방향으로 누적곱

array([-8.09999931e-01,  7.09378659e-01, -7.28738899e-01, -1.16250693e+00,
       -5.27664150e-01,  4.41469790e-01,  7.12228048e-01, -1.14700917e-02,
       -2.87547754e-02, -1.78348767e-02,  1.09595028e-02, -1.92121594e-02,
        1.38560415e-02,  3.53519991e-03, -8.16759480e-04,  1.05156521e-03,
        2.39016356e-03,  4.02731663e-04,  3.22459501e-04,  4.02986695e-04])

In [40]:
arr.cumprod(axis = 0)

array([[-0.80999993, -0.8757762 , -1.02729183,  1.59523107],
       [-0.36766054,  0.73271746, -1.65734116, -0.02569043],
       [-0.92170111,  0.45446105,  1.01843346,  0.04503568],
       [ 0.66474197,  0.11595019, -0.23529509, -0.05798274],
       [ 1.51093059,  0.01953708, -0.18839626, -0.07246266]])

In [14]:
# 인덱싱, 슬라이싱
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2d[2]

array([7, 8, 9])

In [18]:
arr2d[2][2]

9

In [22]:
arr2d[:,0]

array([1, 4, 7])

In [72]:
arr2d[:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
# 다른 방식으로 아래를 출력
# array([[1, 2, 3],
#       [4, 5, 6]])
print(arr2d[[0,1],:])
print(arr2d[[0,2],:])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]


In [61]:
# arr2d에서 [3,6],[[1,2],[4,5]]를 출력하세요.
print(arr2d[:2,2])
print(arr2d[:2,:2])


[3 6]
[[1 2]
 [4 5]]


In [92]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [86]:
# Q. [14,15,16]   ,   [3,9]   ,    [1,7,13] 출력
print(arr[2,(2,3,4)])
print(arr[:2,3])
print(arr[:3,1])

[14 15 16]
[3 9]
[ 1  7 13]


In [90]:
arr3 = np.arange(30).reshape(3,5,2)
arr3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [91]:
arr3[2,1,0]

22

In [94]:
# 배열을 리스트로 변환
li = arr.tolist()
print(li,type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


In [98]:
# Boolean Indexing
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d>5]
print(arr3)
print(arr1d > 5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [108]:
# arr1d에서 일반 인덱스를 이용해서 [6,7,8,9]를 출력
print(arr1d[5:])

[6 7 8 9]


In [109]:
# Q. 1~14까지 ndarray를 만들어 array_e로 저장하고 (array_e / 2)>5를 만족하는 값을 불린 인덱싱으로 출력
array_e = np.arange(1,15)
array_e[array_e/2>5]


array([11, 12, 13, 14])

In [117]:
# Boolean Indexing 활용
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe']) 
data = np.random.randn(7,4)
print(names)
print(data)


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.48126899 -0.72897142 -0.54442609  0.45311098]
 [ 0.06591023  1.5039652  -0.62523699  0.97691528]
 [-2.43830341  1.10446895 -2.45723507 -2.24585643]
 [-0.86732361  0.17823257 -1.55034747  0.87454698]
 [-1.4599284  -0.2525268   0.763225   -0.1990309 ]
 [ 1.6581092  -1.54277232  0.8204385  -0.70790357]
 [ 0.4370787  -0.15415893  0.38879584  0.10042345]]


In [118]:
print(data[names=='Bob'])      # 두개는 같다. 인덱스를 잘 생각해보자
print(data[(0,3),:])

[[ 0.48126899 -0.72897142 -0.54442609  0.45311098]
 [-0.86732361  0.17823257 -1.55034747  0.87454698]]
[[ 0.48126899 -0.72897142 -0.54442609  0.45311098]
 [-0.86732361  0.17823257 -1.55034747  0.87454698]]


In [119]:
print(data[names=='Bob',2:])

[[-0.54442609  0.45311098]
 [-1.55034747  0.87454698]]


In [120]:
# ~는 반대
print(data[names!='Bob'])
print()
cond = names == 'Bob'
print(data[~cond])

[[ 0.06591023  1.5039652  -0.62523699  0.97691528]
 [-2.43830341  1.10446895 -2.45723507 -2.24585643]
 [-1.4599284  -0.2525268   0.763225   -0.1990309 ]
 [ 1.6581092  -1.54277232  0.8204385  -0.70790357]
 [ 0.4370787  -0.15415893  0.38879584  0.10042345]]

[[ 0.06591023  1.5039652  -0.62523699  0.97691528]
 [-2.43830341  1.10446895 -2.45723507 -2.24585643]
 [-1.4599284  -0.2525268   0.763225   -0.1990309 ]
 [ 1.6581092  -1.54277232  0.8204385  -0.70790357]
 [ 0.4370787  -0.15415893  0.38879584  0.10042345]]


In [121]:
# &(and),|(or) 이용가능
mask = (names == 'Bob') | (names == 'Will')
data[mask]
data[(names == 'Bob') | (names == 'Will')]

array([[ 0.48126899, -0.72897142, -0.54442609,  0.45311098],
       [-2.43830341,  1.10446895, -2.45723507, -2.24585643],
       [-0.86732361,  0.17823257, -1.55034747,  0.87454698],
       [-1.4599284 , -0.2525268 ,  0.763225  , -0.1990309 ]])

In [122]:
data[data<0] = 0
print(data)
print()
data[names != 'Joe'] = 7
print(data)

[[0.48126899 0.         0.         0.45311098]
 [0.06591023 1.5039652  0.         0.97691528]
 [0.         1.10446895 0.         0.        ]
 [0.         0.17823257 0.         0.87454698]
 [0.         0.         0.763225   0.        ]
 [1.6581092  0.         0.8204385  0.        ]
 [0.4370787  0.         0.38879584 0.10042345]]

[[7.         7.         7.         7.        ]
 [0.06591023 1.5039652  0.         0.97691528]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [1.6581092  0.         0.8204385  0.        ]
 [0.4370787  0.         0.38879584 0.10042345]]


In [157]:
# [과제] 1~100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지 방식)
li = []
for i in range(1,101):
    if i % 3 == 0:
        li.append(i)
print(li)
a = np.arange(1,101)
print(a[a % 3 == 0])
print(np.extract(a%3==0,a))

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [160]:
# [과제] 1~100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)
li = []
for i in range(1,101):
    if i % 5 == 0 and i % 2 == 0:
        li.append(i)
print(li)
a = np.arange(1,101)
print(a[(a % 5 == 0) & (a % 2 == 0)])
print(np.extract((a%5==0) & (a%2 ==0),a))

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]


In [7]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구해라.
arr = np.random.randn(10000,10000)
print(arr)
print(arr.mean().round())
print(arr.std().round())                      # 표준정규분포의 평균은 0, 표준편차는 1이다.

[[ 2.15604505 -0.02030196  0.20094325 ... -0.92520935  0.60574917
  -0.3707668 ]
 [-0.0050129   0.77231454  1.44397245 ... -0.10725032 -0.92096426
   0.6379752 ]
 [-0.69489854  0.18068084  0.65709857 ... -0.31621366 -0.94678661
  -0.15396084]
 ...
 [ 1.7010919  -1.43114391 -0.2604583  ...  0.50907814 -1.23289763
   0.76699752]
 [-0.93524794 -1.03424903 -0.23919202 ... -2.60917741  0.85259781
   0.39026893]
 [ 0.7376519  -0.25259818 -0.13341694 ...  0.52845284 -1.74349152
   2.13996945]]
0.0
1.0


In [169]:
# [과제] 현재 사용하고 있는 numpy의 버전을 출력
print(np.version.version)
print(np.__version__)

1.21.2
1.21.2


In [8]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [171]:
# [과제] numpy 함수의 도움말 기능을 볼 수 있는 방법을 수행하여 add함수의 가이드를 출력
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [182]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력
# array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [145]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [11]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요
a= np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [12]:
# fancy indexing
arr = np.arange(32).reshape((8,4))
print(arr)
arr[[1,5,7,2],[0,3,1,2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

In [26]:
arr = np.arange(32).reshape(8,4)
print(arr,'\n')

arr[[1,5,7,2],[0,3,1,2]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 



array([ 4, 23, 29, 10])

In [28]:
print(arr[[1,5,7,2]],'\n')
print(arr[[1,5,7,2]][:,(0,3,1,2)])             # 순서 바꾸는 것이 가능

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [32]:
#배열 전치와 축 바꾸기
arr = np.arange(15).reshape(3,5)
print(arr)
print(arr.T)
print(arr.transpose())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
